name: Code Validator

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  Format-Lint-Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
              
      - name: Install Dependencies
        run: pnpm install
      - name: Format any code that needs to be formatted
        run: pnpm format
      - name: Check for lint errors
        run: pnpm lint
      - name: Run all tests
        run: pnpm test
      #- name: Check to pass the coverage threshold
      #  run: pnpm coverage