name: Code Validator

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  Format-Lint-Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: pnpm-setup
        uses: pnpm/action-setup@v2
        with:
          version: 9.3.0

      - name: Install Dependencies
        run: pnpm install
      - name: Format any code that needs to be formatted
        run: pnpm format
      - name: Check for lint errors
        run: pnpm lint
      - name: Run all tests
        run: pnpm test
      #- name: Check to pass the coverage threshold
      #  run: pnpm coverage