name: Code Validator

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  Format-Lint-Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install pnpm
        run: npm i pnpm
      - name: Install Dependencies
        run: pnpm install
      - name: Format any code that needs to be formatted
        run: pnpm format
      - name: Check for lint errors
        run: pnpm lint
      - name: Run all tests
        run: pnpm test
      #- name: Check to pass the coverage threshold
      #  run: pnpm coverage